# Generated by Django 5.2.8 on 2025-12-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_autor_bibliografia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'permissions': (('Ver_Prestamos', 'Puede ver prestamos'), ('Gestionar_Prestamos', 'Puede gestionar prestamos'))},
        ),
    ]
