# Generated by Django 5.2.8 on 2026-01-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_libro_editorial_libro_fecha_libro_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('b', 'Borrador'), ('p', 'Préstamo'), ('m', 'Multa'), ('d', 'Devuelto')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='multa',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='multa',
            name='tipo',
            field=models.CharField(choices=[('r', 'Retraso'), ('p', 'Perdida'), ('d', 'Deterioro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_max',
            field=models.DateField(blank=True, null=True),
        ),
    ]
