# Generated by Django 5.2.8 on 2026-01-05 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_prestamo_estado_alter_multa_monto_alter_multa_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='estado',
        ),
        migrations.AlterField(
            model_name='multa',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='multa',
            name='tipo',
            field=models.CharField(choices=[('r', 'retraso'), ('p', 'perdida'), ('d', 'deterioro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_max',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
