# Generated by Django 5.2.8 on 2026-01-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_remove_prestamo_estado_alter_multa_monto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'permissions': (('ver_prestamos', 'Puede ver prestamos'), ('gestionar_prestamos', 'Puede gestionar prestamos'))},
        ),
        migrations.AlterField(
            model_name='multa',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
