# Generated by Django 5.2.8 on 2026-01-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_multa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='tiene_multa',
            field=models.BooleanField(default=False),
        ),
    ]
