# Generated by Django 5.2.8 on 2026-01-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_prestamo_tiene_multa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
