# Generated by Django 5.2.8 on 2026-01-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_autor_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
