# Generated by Django 5.2.8 on 2026-01-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_libro_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
