# Generated by Django 5.2.8 on 2026-01-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_libro_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
