# Generated by Django 5.2.8 on 2026-01-07 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_libro_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha',
        ),
    ]
