# Generated by Django 5.2.8 on 2026-01-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_remove_libro_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('devuelto', 'Devuelto')], default='solicitado', max_length=20),
        ),
    ]
